districts = [
    "Adilabad", "Kumuram Bheem Asifabad", "Mancherial", "Nirmal",
    "Nizamabad", "Jagitial", "Peddapalli", "Karimnagar", "Rajanna Sircilla",
    "Kamareddy", "Siddipet", "Medak", "Sangareddy", "Vikarabad",
    "Hyderabad", "Medchal Malkajgiri", "Rangareddy", "Yadadri Bhuvanagiri",
    "Jangaon", "Mahabubabad", "Warangal Rural", "Hanumakonda",
    "Mulugu", "Jayashankar Bhupalpally", "Bhadradri Kothagudem",
    "Khammam", "Suryapet", "Nalgonda", "Nagarkurnool",
    "Mahabubnagar", "Wanaparthy", "Jogulamba Gadwal", "Narayanpet"
]

neighbors = {
    "Adilabad": ["Kumuram Bheem Asifabad", "Nirmal"],
    "Kumuram Bheem Asifabad": ["Adilabad", "Mancherial"],
    "Mancherial": ["Kumuram Bheem Asifabad", "Jagitial", "Peddapalli", "Nirmal", "Jayashankar Bhupalpally"],
    "Nirmal": ["Adilabad", "Nizamabad", "Kumuram Bheem Asifabad", "Jagitial", "Mancherial"],
    "Nizamabad": ["Nirmal", "Kamareddy", "Jagitial", "Rajanna Sircilla"],
    "Jagitial": ["Nizamabad", "Mancherial", "Peddapalli", "Rajanna Sircilla", "Nirmal", "Karimnagar"],
    "Peddapalli": ["Mancherial", "Jagitial", "Karimnagar", "Jayashankar Bhupalpally"],
    "Karimnagar": ["Peddapalli", "Rajanna Sircilla", "Hanumakonda", "Jagitial", "Jayashankar Bhupalpally", "Siddipet"],
    "Rajanna Sircilla": ["Jagitial", "Karimnagar", "Siddipet", "Kamareddy", "Nizamabad"],
    "Kamareddy": ["Nizamabad", "Medak", "Sangareddy", "Rajanna Sircilla", "Siddipet"],
    "Siddipet": ["Rajanna Sircilla", "Medak", "Jangaon", "Kamareddy", "Medchal Malkajgiri", "Karimnagar", "Hanumakonda", "Yadadri Bhuvanagiri"],
    "Medak": ["Kamareddy", "Siddipet", "Sangareddy", "Medchal Malkajgiri"], 
    "Sangareddy": ["Medak", "Vikarabad", "Rangareddy", "Medchal Malkajgiri", "Kamareddy"],
    "Vikarabad": ["Sangareddy", "Rangareddy", "Narayanpet", "Mahabubnagar"],
    "Hyderabad": ["Medchal Malkajgiri", "Rangareddy"],
    "Medchal Malkajgiri": ["Hyderabad", "Rangareddy", "Yadadri Bhuvanagiri", "Medak", "Siddipet", "Sangareddy"],
    "Rangareddy": ["Hyderabad", "Vikarabad", "Medchal Malkajgiri", "Mahabubnagar", "Sangareddy", "Nagarkurnool", "Yadadri Bhuvanagiri", "Nalgonda"],
    "Yadadri Bhuvanagiri": ["Medchal Malkajgiri", "Jangaon", "Nalgonda", "Siddipet", "Rangareddy", "Suryapet"],
    "Jangaon": ["Siddipet", "Yadadri Bhuvanagiri", "Hanumakonda", "Warangal Rural", "Mahabubabad", "Suryapet"],
    "Mahabubabad": ["Warangal Rural", "Bhadradri Kothagudem", "Jangaon", "Suryapet", "Khammam", "Mulugu"],
    "Warangal Rural": ["Hanumakonda", "Mahabubabad", "Jayashankar Bhupalpally", "Jangaon", "Mulugu"],
    "Hanumakonda": ["Karimnagar", "Jangaon", "Warangal Rural", "Siddipet", "Jayashankar Bhupalpally"],
    "Mulugu": ["Jayashankar Bhupalpally", "Bhadradri Kothagudem", "Warangal Rural", "Mahabubabad"],
    "Jayashankar Bhupalpally": ["Mulugu", "Peddapalli", "Mancherial", "Karimnagar", "Hanumakonda", "Warangal Rural"],
    "Bhadradri Kothagudem": ["Mulugu", "Mahabubabad", "Khammam"],
    "Khammam": ["Bhadradri Kothagudem", "Suryapet", "Mahabubabad"],
    "Suryapet": ["Khammam", "Nalgonda", "Jangaon", "Mahabubabad", "Yadadri Bhuvanagiri"],
    "Nalgonda": ["Suryapet", "Yadadri Bhuvanagiri", "Nagarkurnool", "Rangareddy"],
    "Nagarkurnool": ["Nalgonda", "Mahabubnagar", "Wanaparthy", "Rangareddy"],
    "Mahabubnagar": ["Rangareddy", "Nagarkurnool", "Narayanpet", "Vikarabad", "Wanaparthy"],
    "Wanaparthy": ["Nagarkurnool", "Jogulamba Gadwal", "Mahabubnagar", "Narayanpet"],
    "Jogulamba Gadwal": ["Wanaparthy", "Narayanpet"],
    "Narayanpet": ["Jogulamba Gadwal", "Mahabubnagar", "Vikarabad", "Wanaparthy"]
}